<!DOCTYPE html>
<html>
<<head>
    <title>Bromwich Farms Home Page</title>
    <meta charset="utf-8">
    <meta name="author" content="Martin" >
    <meta name="Keywords" content="Bromwich Farms Home Page">
    <meta name="Description" content="Home page for grower of Iowa vegetables.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/main.css">
    
    <script src="js/jqueryUI.3.3.1.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/site.js"></script>


</head>
